services:
  koel:
    image: phanan/koel:latest
    container_name: koel

    networks:
      - vpn_net

    ports:
      - "4534:80"

    environment:
      TZ: America/[TimeZone]

    volumes:
      - /mnt/storage/Music:/music
      - ./image-storage:/var/www/html/public/img/storage
      - ./search-indexes:/var/www/html/storage/search-indexes
      - ./logs:/var/www/html/storage/logs
      - ./.env:/var/www/html/.env

    restart: unless-stopped

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  vpn_net:
    external: true