services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin

    user: "${PUID}:${PGID}"

    networks:
      - vpn_net

    environment:
      JELLYFIN_PublishedServerUrl: "${TAILSCALE_IP}:8096"

    volumes:
      - ./config:/config
      - "${VIDEO_PATH}:/media"
      - "${STORAGE_PATH}:/hdd"

    ports:
      - "${JELLYFIN_HTTP_PORT}:8096"
      - "${JELLYFIN_HTTPS_PORT}:8920"

    restart: unless-stopped

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  vpn_net:
    external: true