services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

    volumes:
      - ./config:/config
      - ${BOOKS}:/books
      - ${COMICS}:/comics

    ports:
      - "5000:5000"

    restart: unless-stopped

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      - vpn_net

networks:
  vpn_net:
    external: true