services:
  smbshare:
    image: dperson/samba:latest

    container_name: smbshare

    networks:
      - vpn_net

    environment:
      - USERID=${PUID}
      - GROUPID=${PGID}
      - TZ=${TZ}

    volumes:
      - ${PATH}:/PATH

    command: >
      -u "${SAMBA_USER};${SAMBA_PASSWORD}"
      -s "Path;/PATH;yes;no;no;${SAMBA_USER}"
      -p

    ports:
      - "139:139"
      - "445:445"

    restart: unless-stopped

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  vpn_net:
    external: true