services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb

    networks:
      - vpn_net

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - ./data:/var/lib/mysql

    restart: unless-stopped

networks:
  vpn_net:
    external: true